export const CATEGORIES = [
  {
    name: 'Καφέδες',
    items: [
      { name: 'Freddo espresso', price: 3.5 },
      { name: 'Freddo cappuccino', price: 4 },
      { name: 'Espresso', price: 3 },
      { name: 'Cappuccino', price: 3.5 },
      { name: 'Americano', price: 3.5 },
      { name: 'Ελληνικός', price: 2.5 },
      { name: 'Σοκολάτα', price: 4 },
      { name: 'Nescafe', price: 3 },
      { name: 'Nescafe φραπέ', price: 3 },
      { name: 'Latte', price: 4.5 },
      { name: 'Καφές φίλτρου', price: 3 },
      { name: 'Κακάο', price: 3 },
      { name: 'Macchiato', price: 3.5 },
      { name: 'Mochaccino', price: 5 },
      { name: 'Σοκολάτα βιενουά', price: 4.5 },
    ],
  },
  {
    name: 'Αναψυκτικά',
    items: [
      { name: 'Fanta Πορτοκαλάδα', price: 3.5 },
      { name: 'Sprite', price: 3.5 },
      { name: 'Fanta Λεμονάδα', price: 3.5 },
      { name: 'Coca Cola', price: 3.5 },
      { name: 'Coca Cola Zero', price: 3.5 },
      { name: 'Τσάι Ροδάκινο', price: 3.5 },
      { name: 'Τσάι Λεμόνι', price: 3.5 },
      { name: 'Τσάι Πράσινο', price: 3.5 },
      { name: 'Τσάι Ζεστό', price: 3.5 },
      { name: 'Red Bull', price: 5 },
      { name: 'Σόδα', price: 3.5 },
      { name: 'Νερό Μικρό', price: 0.5 },
      { name: 'Νερό Μεγάλο', price: 1.5 },
      { name: 'Perrier', price: 3.5 },
      { name: 'Schweppes Πορτοκάλι', price: 3.5 },
      { name: 'Schweppes Λεμόνι', price: 3.5 },
      { name: 'Schweppes Pink', price: 3.5 },
      { name: 'Tonic', price: 3.5 },
      { name: '3 cents Pink', price: 4 },
      { name: '3 cents Ginger', price: 4 },
      { name: 'Σπιτική Λεμονάδα', price: 6 },
      { name: 'Σπιτική 9 Φρούτα', price: 6 },
      { name: 'Σπιτική Κερασάδα', price: 6 },
      { name: 'Σπιτική Ροδακινάδα', price: 6 },
      { name: 'Σπιτική Ροζ Λεμονάδα', price: 6 },
      { name: 'Σπιτική Πράσινο Μήλο - Ρόδι', price: 6 },
      { name: 'Παγωτό', price: 2.5 },
    ],
  },
  {
    name: 'Χυμοί',
    items: [
      { name: 'Φυσικός Χυμός', price: 5 },
      { name: 'Χυμός Πορτοκάλι', price: 3.5 },
      { name: 'Χυμός Ανάμεικτος', price: 3.5 },
      { name: 'Χυμός Βύσσινο', price: 3.5 },
      { name: 'Χυμός Μπανάνα', price: 3.5 },
      { name: 'Χυμός Μήλο', price: 3.5 },
      { name: 'Χυμός Ανάνα', price: 3.5 },
      { name: 'Χυμός Βερίκοκο', price: 3.5 },
      { name: 'Χυμός Ροδάκινο', price: 3.5 },
      { name: 'Χυμός Μανταρίνι', price: 3.5 },
      { name: 'Χυμός Φράουλα', price: 3.5 },
      { name: 'Χυμό Μικρό Παιδικό', price: 1.5 },
    ],
  },
  {
    name: 'Τοστ - Κρέπες',
    items: [
      { name: 'Τοστ', price: 2.5, materials: true },
      { name: 'Κρέπα αλμυρή', price: 3, materials: true },
      { name: 'Κρέπα γλυκιά', price: 3.5, materialsSweet: true },
    ],
  },
  {
    name: 'Μπύρες',
    items: [
      { name: 'Βαρέλι Μικρό', price: 4 },
      { name: 'Βαρέλι Μεγάλο', price: 5 },
      { name: 'Kaiser', price: 4 },
      { name: 'Radler', price: 4 },
      { name: 'Άλφα', price: 4 },
      { name: 'Μύθος', price: 4 },
      { name: 'Heineken', price: 4 },
      { name: 'Amstel', price: 4 },
      { name: 'Corona', price: 6 },
      { name: 'Βεργίνα', price: 4 },
      { name: 'Βεργίνα Weiss', price: 6 },
      { name: 'Βεργίνα Red', price: 6 },
      { name: 'Βεργίνα 0%', price: 4 },
      { name: 'Fix dark', price: 4 },
      { name: 'Heineken 0%', price: 4 },
      { name: 'Seven Seals', price: 5 },
    ],
  },
  {
    name: 'Ποτά - Κρασιά',
    items: [
      { name: 'Ποτό Απλό', price: 7 },
      { name: 'Ποτό Σπέσιαλ', price: 8 },
      { name: 'Ποτό Πρίμιουμ', price: 12 },
      { name: 'Κρασί ποτήρι', price: 6 },
      { name: 'Σφηνάκι', price: 3 },
      { name: 'Ρετσίνα Βασιλική', price: 6 },
      { name: 'Bianco Νero λευκό', price: 6 },
      { name: 'Bianco Nero αφρώδες', price: 6 },
      { name: 'Bianco Nero αφρώδες Ροζέ', price: 6 },
      { name: 'Λειβαδιώτη μπουκαλάκι', price: 6 },
      { name: 'Gordons Space', price: 5 },
      { name: 'Παράγκα Μπουκάλι', price: 30 },
      { name: 'Σαμαρόπετρα Μπουκάλι', price: 35 },
      { name: 'Μαλαγουζιά Μπουκάλι', price: 35 },
      { name: 'Φιάλη Απλή', price: 70 },
      { name: 'Φιάλη Σπέσιαλ', price: 80 },
      { name: 'Φιάλη Premium', price: 120 },
    ],
  },
  {
    name: 'Cocktails',
    items: [
      { name: 'Paloma', price: 10 },
      { name: 'Sex on the beach', price: 10 },
      { name: 'Caipiroska', price: 10 },
      { name: 'Daiquiri', price: 10 },
      { name: 'Zombie', price: 10 },
      { name: 'Mojito', price: 10 },
      { name: 'Cosmopolitan', price: 10 },
      { name: 'Margarita', price: 10 },
      { name: 'Caipirinha', price: 10 },
      { name: 'Negroni', price: 10 },
      { name: 'Aperol spritz', price: 10 },
      { name: 'Mai tai', price: 10 },
      { name: 'Long island', price: 10 },
      { name: 'Pina colada', price: 10 },
      { name: 'Bloody Mary', price: 10 },
      { name: 'Porn Star Martini', price: 10 },
      { name: 'KYOTO', price: 10 },
      { name: 'El Sol (Mocktail)', price: 10 },
      { name: 'Mojito Green Apple (Mocktail)', price: 10 },
      { name: 'Yuzi gun', price: 11 },
      { name: 'Cucu splash', price: 11 },
      { name: 'Passion paradise', price: 11 },
      { name: 'Green Apple Perfume', price: 11 },
      { name: "Bartender's choice", price: 10 },
    ],
  },
  {
    name: 'Πρωινό',
    items: [
      { name: 'Ομελέτα', price: 7.5, materials: true },
      { name: 'Καγιανάς', price: 8 },
      { name: 'Αυγά τηγανητά με μπέικον', price: 7 },
      { name: 'Αυγά σκραμπλ', price: 7 },
      { name: 'Αυγά σκραμπλ Με Σολομό', price: 8 },
      { name: 'Pan cake Πραλίνα', price: 7.5, materialsSweet: true },
      { name: 'Pan cake Μέλι Κανέλα', price: 7.5 },
      { name: 'Pan cake Πραλίνα με Μπανάνα κ Φουντούκια', price: 9 },
      { name: 'Pan cake Αλμυρό', price: 9 },
      { name: 'Αυγόφετες', price: 7 },
      { name: 'Γλυκιές Αυγόφετες με Μέλι και Κανέλα', price: 7 },
      { name: 'Γιαούρτι με Φρούτα Εποχής', price: 7 },
      { name: 'Γιαούρτι με Musli', price: 7 },
      { name: 'Πρωινό για Δύο', price: 25 },
    ],
  },
  {
    name: 'Club sandwich',
    items: [
      { name: 'Club sandwich', price: 10.5 },
      { name: 'Club Sandwich Caesar Κοτόπουλο', price: 12.5 },
      { name: 'Club Sandwich με Γύρο', price: 12.5 },
      { name: 'Club πανσέτας', price: 13 },
      { name: 'Club Καλαμάρι', price: 12 },
    ],
  },
  {
    name: 'Junior menu',
    items: [
      { name: 'Junior 1 (Burger)', price: 7.5 },
      { name: 'Junior 2 (Nuggets)', price: 7.5 },
    ],
  },
  {
    name: 'Ούζο-Μεζέδες',
    items: [
      { name: 'Ούζο ποτήρι', price: 3 },
      { name: 'Τσίπουρο ποτήρι', price: 3 },
      { name: 'Μεζέδες', price: 3 },
      { name: 'Μπουκάλι Ούζο', price: 6 },
      { name: 'Αποστολάκι', price: 10 },
      { name: 'Ηδωνικό', price: 10 },
      { name: 'Καραφάκι Κρασί 1/2', price: 12 },
      { name: 'Μπακαλιαράκια', price: 10 },
      { name: 'Γάμπαρι', price: 10 },
    ],
  },
  {
    name: 'Pinsa',
    items: [
      { name: 'Pinsa 21', price: 14 },
      { name: 'Pinsa Special', price: 13 },
      { name: 'Pinsa Πεπερόνι', price: 12.5 },
      { name: 'Pinsa Μαργαρίτα', price: 12 },
    ],
  },
  {
    name: 'Ζυμαρικά',
    items: [
      { name: 'Bolognesa', price: 11 },
      { name: 'Carbonara', price: 11 },
      { name: 'Pasta 21', price: 11 },
      { name: 'Πέννες με Κοτόπουλο', price: 12 },
      { name: 'Πέννες 4 Τυριά', price: 11 },
      { name: 'Γαριδομακαρονάδα', price: 19 },
      { name: 'Μακαρονάδα Θαλασσινών', price: 19 },
    ],
  },
  {
    name: 'Hot dogs - Burgers',
    items: [
      { name: 'Hot dog', price: 7, materials: true },
      { name: 'Burger 21', price: 12.5 },
      { name: 'Burger BBQ', price: 11.5 },
      { name: 'Burger Κοτόπουλο', price: 11.5 },
      { name: 'Double cheese burger', price: 11.5 },
      { name: 'Chicken Crispy Burger', price: 11.5 },
      { name: 'Chili Chicken Crispy Burger', price: 12.5 },
      { name: 'Smash Burger', price: 12.5 },
      { name: 'Burger Λαχανικών', price: 10.5 },
      { name: 'Row No Meat Burger', price: 12.5 }
    ],
  },
  {
    name: 'Bao buns',
    items: [
      { name: 'Shrimp chili bao', price: 9 },
      { name: 'Nuggets bao', price: 8 },
      { name: 'Pulled pork bao', price: 8 },
      { name: 'Bao Νηστίσιμο', price: 8 },
    ],
  },
  {
    name: 'Σαλάτες',
    items: [
      { name: 'Σαλάτα Caesar', price: 10.5 },
      { name: 'Σαλάτα 21', price: 11 },
      { name: 'Σαλάτα Caprese', price: 9 },
      { name: 'Σαλάτα Κουκουβάγια', price: 9 },
      { name: 'Σαλάτα Xωριάτικη', price: 9 },
      { name: 'Σαλάτα Σεφ', price: 11 },
      { name: 'Σαλάτα 21 με Γαρίδες', price: 11 },
      { name: 'Ποικιλία τυριών', price: 12 },
    ],
  },
  {
    name: 'Κυρίως πιάτα',
    items: [
      { name: 'Χοιρινή Πανσετομπριζόλα', price: 18 },
      { name: 'Κοτοπουλάκια Nuggets', price: 12 },
      { name: 'Chicken nuggets a la crème', price: 13 },
      { name: 'Καλαμαράκια τηγανητά', price: 12 },
      { name: 'Σολομός Tεριγιάκι με Λαχανικά', price: 18 },
      { name: 'Μπούτι κοτόπουλο', price: 13 },
      { name: 'Μπιφτέκι', price: 12.5 },
      { name: 'Γύρος χοιρινός', price: 12 },
      { name: 'Mix grill', price: 18 },
      { name: 'Πατάτες Τηγανιτές', price: 5 },
      { name: 'Country Πατάτες', price: 6 },
      { name: 'Πατάτες Τηγανητές Cheddar Bacon', price: 7 },
      { name: 'Ψητά Λαχανικά', price: 6 },
      { name: 'Πίτες extra', price: 1.5 },
      { name: 'Κουβέρ', price: 1.5 },
    ],
  }
];

export const EXTRALIST = [
  { name: 'κασέρι', price: 0.5 },
  { name: 'ζαμπόν', price: 0.5 },
  { name: 'γαλοπούλα', price: 0.5 },
  { name: 'κοτομπουκιές', price: 1 },
  { name: 'κασεροκροκέτα', price: 1 },
  { name: 'μπέικον', price: 0.5 },
  { name: 'ντομάτα', price: 0.5 },
  { name: 'αυγό', price: 1 },
  { name: 'φέτα', price: 1 },
  { name: 'μανιτάρια', price: 0.5 },
  { name: 'χτυπητή', price: 0.5 },
  { name: 'μαγιονέζα', price: 0.5 },
  { name: 'πατατάκια', price: 1 },
  { name: 'sauce μουστάρδας', price: 0.5 },
  { name: 'καπνιστή μπριζόλα', price: 0.5 },
  { name: 'πεπερόνι', price: 0.5 },
  { name: 'σαλάμι μπύρας', price: 0.5 },
  { name: 'μορταδέλα', price: 0.5 },
  { name: 'philadelphia', price: 1 },
  { name: 'πάριζα', price: 0.5 },
  { name: 'κοτόπουλο', price: 1 },
  { name: 'πιπεριά', price: 0.5 },
  { name: 'καλαμπόκι', price: 0.5 },
  { name: 'ελιές', price: 0.5 },
  { name: 'ρωσική', price: 0.5 },
  { name: 'πατάτες τηγανητές', price: 1 },
  { name: 'ουγγαρέζα', price: 0.5 },
  { name: 'κηπουρού', price: 0.5 },
  { name: 'πάπρικα', price: 0.5 },
  { name: 'μανούρι', price: 1 },
  { name: 'λουκάνικο', price: 1 },
  { name: 'σαλάμι αέρος', price: 0.5 },
  { name: 'μελιτζανοσαλάτα', price: 0.5 },
  { name: 'τσένταρ', price: 0.5 },
].map((extra) => ({ ...extra, selected: false }));

export const EXTRALISTSWEET = [
  { name: 'Μερέντα', price: 0.5 },
  { name: 'Nutella', price: 1 },
  { name: 'Μπισκότο', price: 0.5 },
  { name: 'Μπανάνα', price: 0.5 },
  { name: 'Λευκή Πραλίνα', price: 0.5 },
  { name: 'Bueno Πραλίνα', price: 0.5 },
  { name: 'Φράουλα Πραλίνα', price: 0.5 },
  { name: 'Παγωτό', price: 2.5 },
  { name: 'Μπισκότο Oreo', price: 0.5 },
  { name: 'Φράουλα Κομματάκια', price: 1 },
  { name: 'Bueno Κομματάκια', price: 1 },
  { name: 'Καρύδι', price: 0.5 },
  { name: 'Φουντούκι', price: 0.5 },
  { name: 'Αμύγδαλο', price: 0.5 },
  { name: 'Lila pause', price: 1.5 },
  { name: 'Lotus Μπισκότο', price: 1.5 },
  { name: 'Smarties', price: 1 },
  { name: 'Mars', price: 1 },
  { name: 'Twix', price: 1 },
  { name: 'Μαρμελάδα φράουλα', price: 0.5 },
  { name: 'Μαρμελάδα ροδάκινο', price: 0.5 },
  { name: 'Caprice', price: 1 },
].map((extra) => ({ ...extra, selected: false }));
